version: '3.8'

services:
  nwc_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
